name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Update feeds
        run:|
          ./scripts/feeds update -a
          ./scripts/feeds install -a
    - name: Make download
        run:|
          make download -j8
    - name: Compile firmware
        run:|
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
    - name: Assemble artifact
        run:|
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
